[theme]
primaryColor = "#ff0000"  # Vermelho
backgroundColor = "#000000"  # Preto
secondaryBackgroundColor = "#1e1e1e"  # Cinza escuro
textColor = "#ffffff"  # Branco
font = "monospace"  # Altere para uma fonte diferente
